name: gidosa-fullstack1-admin prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-codedeploy:
    environment: prod
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4


